### ISSUE TITLE
[Question] Can this work with HTML editor

### ISSUE THREAD

**Issue by brohlson** [datocms/gatsby-remark-images-datocms#1]
This doesn't seem to work when using the HTML editor instead of the Markdown editor - is that correct functionality or am I missing something?

```javascript
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images-datocms',
            options: {
              apiToken: siteConfig.dato,
              maxWidth: 800,
              backgroundColor: '#0EA5BA',
            },
          },
        ],
      },
    },
```

**Comment by matjack1** [comment]
Sorry about not giving you a feedback before, but it's correct. You can only use it on MD editors for now. We've noted down the suggestion, but I'm going to close this issue as we are not going to act on this soon. But feel free to get back here if you have any additional info/requests.
