### ISSUE TITLE
Default setup from docs, missing options and weird image results

### ISSUE THREAD

**Issue by wildpow** [datocms/gatsby-remark-images-datocms#3]
Getting weird results from markdown images with the setup from the readme. I started digging through the docs for [gatsby-remark-images](https://www.gatsbyjs.com/plugins/gatsby-remark-images/). and I found a few options that are not listed in this repo's docs like `withWebp `, `quality`, etc. The `tracedSVG` option solved my issue but, I don't see the SVG effect (even on Chrome's Fast 3G preset), even though HTML output is effected. Is `tracedSVG` not fully implemented and that's why it's not listed in the docs?

## Default setup from this plug-ins docs:
<img src="https://user-images.githubusercontent.com/17464319/90069893-d3d7b600-dca7-11ea-8a6e-322105f0714c.png" width=400 />

<img width="1137" alt="Screen Shot 2020-08-12 at 2 44 44 PM" src="https://user-images.githubusercontent.com/17464319/90071628-c53ece00-dcaa-11ea-8ab9-c4842d94d39e.png">

[screen capture before](https://youtu.be/NWGJRrAwA6w)

## Adding `tracedSVG` to options:
<img src="https://user-images.githubusercontent.com/17464319/90070703-29609280-dca9-11ea-90b3-4c6a54b7753a.png" width=400 />

<img width="1150" alt="Screen Shot 2020-08-12 at 2 43 26 PM" src="https://user-images.githubusercontent.com/17464319/90071481-7e50d880-dcaa-11ea-94db-f80371371ad5.png">

[screen capture after](https://www.youtube.com/watch?v=DrH7iFiJZT8)

Let me know if you need any more info. I would love to try and fix this and or add the ability to use `gatsby-remark-images` options but, it may be a little bit over my head. I will try 😄

**Comment by wildpow** [comment]
I've been testing different images in my markdown and I believe I've narrowed down these blurry image results to a certain file format. First one is a `.png` and second is `jpg`
![Screen Shot 2020-08-31 at 6 53 48 PM](https://user-images.githubusercontent.com/17464319/91786158-d600a680-ebbb-11ea-942a-bf697477e5b6.png)

Tomorrow I'll test converting the original images in my first post to see if this hypothesis holds true.

**Comment by stefanoverna** [comment]
Uh, I think I understand. What you're seeing is two layers: the transparent high-quality PNG on top, and the LQIP below

**Comment by wildpow** [comment]
So no fix?

**Comment by stefanoverna** [comment]
We have no way of fixing it ourselves @wildpow, that's just how gatsby-image works 😕 
I would suggest creating an issue there and see what they think about! If you can please reference this issue in the new one over gatsby, so we can get updates also here!
